CREATE TABLE patch (
  id SERIAL NOT NULL PRIMARY KEY,
  short_id CHAR(12) NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  patch_data JSONB NOT NULL
);
